### ISSUE TITLE
LSP needs restart when first loaded

### ISSUE THREAD

**Issue by mobilex1122** [monkoose/DoNe#2]
When I first open neovim-defould it doen't load the LSP correctly

![2024-11-02-113142_hyprshot](https://github.com/user-attachments/assets/0f594ac3-e004-40e6-9883-db9e2eed8c01)

I first need to run `:LspRestart`

![2024-11-02-113250_hyprshot](https://github.com/user-attachments/assets/ddcca853-0d77-4a73-9970-fc2c77e619bd)

To actually get the LSP to stop complaining about defold global variables.

![2024-11-02-113303_hyprshot](https://github.com/user-attachments/assets/20f92201-2966-4f7b-b4aa-0c3fa2070b79)

**Comment by monkoose** [comment]
It is up to a user how to properly load their plugins. 

First of all DoNe is configured for built-in lsp, not lspconfig (even though it is just a wrapper of the built-in lsp, it still can introduce some bugs (was the case for me in the past). But at the time of the creation of the plugin I have tested and it have worked with lspconfig for me without restarts.

Seems like your config attaches a buffer to lsp before DoNe registers autocmd "LspAttach", so it never executed.
Try to change the order of the plugins in your package manager, or you have messed up with some lazy loading.

In any case you can for example with `lazy.nvim` package manager add `:LspRestart` command to the DoNe config
```lua
   config = function()
     vim.cmd.LspRestart()
  end
```
